# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ucd_robot/SystemState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SystemState(genpy.Message):
  _md5sum = "13c814d1fd4a9cbdec20374044113342"
  _type = "ucd_robot/SystemState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool system_state 
bool sensor_state
bool gripper_state
bool robot_state
bool camera_state"""
  __slots__ = ['system_state','sensor_state','gripper_state','robot_state','camera_state']
  _slot_types = ['bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       system_state,sensor_state,gripper_state,robot_state,camera_state

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SystemState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.system_state is None:
        self.system_state = False
      if self.sensor_state is None:
        self.sensor_state = False
      if self.gripper_state is None:
        self.gripper_state = False
      if self.robot_state is None:
        self.robot_state = False
      if self.camera_state is None:
        self.camera_state = False
    else:
      self.system_state = False
      self.sensor_state = False
      self.gripper_state = False
      self.robot_state = False
      self.camera_state = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5B().pack(_x.system_state, _x.sensor_state, _x.gripper_state, _x.robot_state, _x.camera_state))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.system_state, _x.sensor_state, _x.gripper_state, _x.robot_state, _x.camera_state,) = _get_struct_5B().unpack(str[start:end])
      self.system_state = bool(self.system_state)
      self.sensor_state = bool(self.sensor_state)
      self.gripper_state = bool(self.gripper_state)
      self.robot_state = bool(self.robot_state)
      self.camera_state = bool(self.camera_state)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5B().pack(_x.system_state, _x.sensor_state, _x.gripper_state, _x.robot_state, _x.camera_state))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.system_state, _x.sensor_state, _x.gripper_state, _x.robot_state, _x.camera_state,) = _get_struct_5B().unpack(str[start:end])
      self.system_state = bool(self.system_state)
      self.sensor_state = bool(self.sensor_state)
      self.gripper_state = bool(self.gripper_state)
      self.robot_state = bool(self.robot_state)
      self.camera_state = bool(self.camera_state)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5B = None
def _get_struct_5B():
    global _struct_5B
    if _struct_5B is None:
        _struct_5B = struct.Struct("<5B")
    return _struct_5B
