// Generated by gencpp from file ucd_robot/DataState.msg
// DO NOT EDIT!


#ifndef UCD_ROBOT_MESSAGE_DATASTATE_H
#define UCD_ROBOT_MESSAGE_DATASTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ucd_robot
{
template <class ContainerAllocator>
struct DataState_
{
  typedef DataState_<ContainerAllocator> Type;

  DataState_()
    : bias_state(false)
    , buffer_state(false)  {
    }
  DataState_(const ContainerAllocator& _alloc)
    : bias_state(false)
    , buffer_state(false)  {
  (void)_alloc;
    }



   typedef uint8_t _bias_state_type;
  _bias_state_type bias_state;

   typedef uint8_t _buffer_state_type;
  _buffer_state_type buffer_state;





  typedef boost::shared_ptr< ::ucd_robot::DataState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ucd_robot::DataState_<ContainerAllocator> const> ConstPtr;

}; // struct DataState_

typedef ::ucd_robot::DataState_<std::allocator<void> > DataState;

typedef boost::shared_ptr< ::ucd_robot::DataState > DataStatePtr;
typedef boost::shared_ptr< ::ucd_robot::DataState const> DataStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ucd_robot::DataState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ucd_robot::DataState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ucd_robot::DataState_<ContainerAllocator1> & lhs, const ::ucd_robot::DataState_<ContainerAllocator2> & rhs)
{
  return lhs.bias_state == rhs.bias_state &&
    lhs.buffer_state == rhs.buffer_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ucd_robot::DataState_<ContainerAllocator1> & lhs, const ::ucd_robot::DataState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ucd_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ucd_robot::DataState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ucd_robot::DataState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ucd_robot::DataState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ucd_robot::DataState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ucd_robot::DataState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ucd_robot::DataState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ucd_robot::DataState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e4df093d868adffe6bda0f3e2ebd1f68";
  }

  static const char* value(const ::ucd_robot::DataState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe4df093d868adffeULL;
  static const uint64_t static_value2 = 0x6bda0f3e2ebd1f68ULL;
};

template<class ContainerAllocator>
struct DataType< ::ucd_robot::DataState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ucd_robot/DataState";
  }

  static const char* value(const ::ucd_robot::DataState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ucd_robot::DataState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool bias_state\n"
"bool buffer_state\n"
;
  }

  static const char* value(const ::ucd_robot::DataState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ucd_robot::DataState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bias_state);
      stream.next(m.buffer_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DataState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ucd_robot::DataState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ucd_robot::DataState_<ContainerAllocator>& v)
  {
    s << indent << "bias_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bias_state);
    s << indent << "buffer_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.buffer_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UCD_ROBOT_MESSAGE_DATASTATE_H
